### ISSUE TITLE
After using software to use iPad as a display, it can only respond to sliding gestures

### ISSUE THREAD

**Issue by lemonno2333** [Leapward-Koex/MaiTouchSensorEmulator#3]
It has been confirmed that touching in other software is normal, and the same problem will occur after changing to different streaming software.

https://github.com/Leapward-Koex/MaiTouchSensorEmulator/assets/49359040/54dc5876-b999-44fc-98c5-2887626b2aae

Because of the translation software, I didn’t know if I could explain the question correctly, so I recorded a video

**Comment by Leapward-Koex** [comment]
What software are you using to use your iPad as a display? I tried [spacedesk](https://www.spacedesk.net/) and it worked as expected for me.

**Comment by lemonno2333** [comment]
I am using duet

**Comment by Leapward-Koex** [comment]
Is there any other steps to reproduce this issue?

For me it works as expected for me using duet server 2.7.3.0 with duet app A2.24.0.0 on a 6th gen iPad, connected wirelessly.

[Duet.webm](https://github.com/Leapward-Koex/MaiTouchSensorEmulator/assets/30615050/857918d6-5217-473c-ad7b-08e1c3e44419)

**Comment by lemonno2333** [comment]
I'm using the same software version as you, but it's the same problem whether wired or wireless, even if I restart my iPad and computer.
The problem still exists after I reinstalled Duet on the computer.
Sorry this problem has existed since I started using 1. I don't know how to reproduce it. It happens when I use 1 on my device.
My device is iPad Pro 2021, and the computer version is Windows 10 22H2.
I tried Spacedesk again yesterday, and it did work normally. However, the delays in Spacedesk's wired and wireless connections were so large that I couldn't play normally.

**Comment by lemonno2333** [comment]
When I changed to another computer, 1 ran normally. Maybe Microsoft or my antivirus software broke something.
Anyway, thank you very much for your willingness to accompany me to analyze the problem. I'm sorry for taking up your time. I wish you a happy life.
