### ISSUE TITLE
PC not detecting my device as COM 3

### ISSUE THREAD

**Issue by NekoYaka** [Leapward-Koex/MaiTouchSensorEmulator#4]
I installed the files and followed the steps to locate COM3 and delete it for the driver but my PC cant detect it to begin with. 
![issue](https://github.com/Leapward-Koex/MaiTouchSensorEmulator/assets/172360134/3b91a573-eafd-400f-8950-c6c2dba5e27c)

**Comment by Leapward-Koex** [comment]
Its fine if your computer doesn't have a COM3 device listed there, you can ignore the step to uninstall. It's just that certain USB peripherals will occupy the COM3 port which interferes with how Sinmai works as it expects touch data to be fed over the COM3 port.

After pressing the "Install com port" button in the app it should create an entry like this in device manager.
![image](https://github.com/Leapward-Koex/MaiTouchSensorEmulator/assets/30615050/5c97c552-7056-4786-886a-60dbd5318e95)

It will be correct if you press the "List installed com ports" button and the list contains COM3 and COM23.
e.g.
![image](https://github.com/Leapward-Koex/MaiTouchSensorEmulator/assets/30615050/b8dd89df-ee8e-41a0-ae3c-e52f9f221afc)

If the app fails to install the COM port then that's another issue and please let me know about it.

**Comment by NekoYaka** [comment]
So the app installed com3 and com23 and everything works properly but now I have the issue where the game doesn't register the inputs even though the emulator is registering it.

https://github.com/Leapward-Koex/MaiTouchSensorEmulator/assets/172360134/4b96098d-c597-4a07-8484-8dcf193cb9cb
