### ISSUE TITLE
App detecting input but game isn't registering it.

### ISSUE THREAD

**Issue by NekoYaka** [Leapward-Koex/MaiTouchSensorEmulator#5]
I managed to get everything set up fine with both the COM 3 and COM 23 ports set up. After I boot up the emulator with the game the emulator registers my input but the game doesn't recieve it.

https://github.com/Leapward-Koex/MaiTouchSensorEmulator/assets/172360134/c90cf299-958b-4573-a2cc-4b50075dd08f

**Comment by Leapward-Koex** [comment]
Regardless of this, I have made a new version [1.3.0](https://github.com/Leapward-Koex/MaiTouchSensorEmulator/releases/tag/1.3.0) that has an option to emulate the ring buttons via keyboard events. 
Can you try this version and see if it helps your issue?
