### ISSUE TITLE
Adding suggestions!

### ISSUE THREAD

**Issue by ginoong25** [Leapward-Koex/MaiTouchSensorEmulator#8]
Thank you for your hard work!

I tried this with my Dell P2314T (170Hz polling rate) Touchscreen monitor and can surprisingly play casually Max Level 13+!
I have some suggestions that might help with the experience especially running on a single monitor with touchscreen on it.

- An ability to minimize the configuration window (when using the touch emulator, it shows up)
- The touch window covers the entire screen when it detects sensor window positioning so when it goes out of bounds, it won't select the background window.
- A customizable border would be great as well!

Hope this would be possible (at least the first two)! Thank you so much!

**Comment by Leapward-Koex** [comment]
Good to hear that it works well on higher difficulties!

I've implemented your suggestions in 1.4.0
https://github.com/Leapward-Koex/MaiTouchSensorEmulator/releases/tag/1.4.0

Thanks!
